# 1.Bibliotecas

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

#2. Preparação dos dados

In [8]:
df = pd.read_csv('../data/processed/churn_tratado.csv')

#3. Analise estatistica das variaveis numericas

##3.1 **tenure** x **Churn**

In [10]:
tenure_churn = df[df['Churn']=='Yes']['tenure']
tenure_no_churn = df[df['Churn']=='No']['tenure']

In [15]:
print(tenure_churn.describe())
print(tenure_no_churn.describe())

count    1869.000000
mean       17.979133
std        19.531123
min         1.000000
25%         2.000000
50%        10.000000
75%        29.000000
max        72.000000
Name: tenure, dtype: float64
count    5174.000000
mean       37.569965
std        24.113777
min         0.000000
25%        15.000000
50%        38.000000
75%        61.000000
max        72.000000
Name: tenure, dtype: float64

In [13]:
len(tenure_churn), len(tenure_no_churn)

(1869, 5174)

In [16]:
stats.mannwhitneyu(
    tenure_churn,
    tenure_no_churn,
    alternative='two-sided'
)

MannwhitneyuResult(statistic=np.float64(2515538.0), pvalue=np.float64(2.419635517951866e-208))

### Resultado

O teste de Mann–Whitney tem `p-value < 0,05`, mostrando que há diferença entre as distribuições de **tenure** dos grupos `Churn = Yes` e `Churn = No`.

Esse resultado confirma estatisticamente a diferença que vimos durante a análise exploratória, onde os clientes que realizaram churn apresentaram valores menor **tenure**.

Ainda não podemos dizer que tenure causa churn.

##3.2 **MonthlyCharges** x **Churn**

In [23]:
month_churn = df[df['Churn']=='Yes']['MonthlyCharges']
month_no_churn = df[df['Churn']=='No']['MonthlyCharges']

In [21]:
print(month_churn.describe())
print(month_no_churn.describe())

count    1869.000000
mean       74.441332
std        24.666053
min        18.850000
25%        56.150000
50%        79.650000
75%        94.200000
max       118.350000
Name: MonthlyCharges, dtype: float64
count    5174.000000
mean       61.265124
std        31.092648
min        18.250000
25%        25.100000
50%        64.425000
75%        88.400000
max       118.750000
Name: MonthlyCharges, dtype: float64

In [26]:
stats.mannwhitneyu(
    month_churn,
    month_no_churn,
    alternative="two-sided"
)

MannwhitneyuResult(statistic=np.float64(6003125.5), pvalue=np.float64(3.311627651988585e-54))

### Resultado

O teste de Mann–Whitney tem `p-value < 0,05`, mostrando que tem diferença entre as distribuições de **MonthlyCharges** dos grupos `Churn = Yes` e `Churn = No`.

Esse resultado confirma estatisticamente a diferença que vimos na análise exploratória, onde os clientes que realizaram churn apresentaram valores de **MonthlyCharges** geralmente maiores.

Ainda não podemos dizer que MonthlyCharges causa churn.

##3.3 **TotalCharges** x **Churn**

In [27]:
total_churn = df[df['Churn']=='Yes']['TotalCharges']
total_no_churn = df[df['Churn']=='No']['TotalCharges']

In [28]:
print(total_churn.describe())
print(total_no_churn.describe())

count    1869.000000
mean     1531.796094
std      1890.822994
min        18.850000
25%       134.500000
50%       703.550000
75%      2331.300000
max      8684.800000
Name: TotalCharges, dtype: float64
count    5174.000000
mean     2549.911442
std      2329.954215
min         0.000000
25%       572.900000
50%      1679.525000
75%      4262.850000
max      8672.450000
Name: TotalCharges, dtype: float64

In [31]:
stats.mannwhitneyu(
    total_churn,
    total_no_churn,
    alternative="two-sided"
)

MannwhitneyuResult(statistic=np.float64(3381224.0), pvalue=np.float64(5.685033866207314e-83))

###Resultado

O teste de Mann–Whitney apresentou p-value < 0,05, indicando que existe uma diferença estatisticamente significativa entre as distribuições de TotalCharges dos grupos Churn = Yes e Churn = No.

Esse resultado confirma estatisticamente a diferença observada na análise exploratória, onde os clientes que realizaram churn apresentaram valores de TotalCharges geralmente menores.

Ainda não podemos dizer que TotalCharges causa churn.

# 4. Analise estatistica das variaveis categoricas

## 4.1 **Contract** × **Churn**

In [40]:
tabela_cont_C = pd.crosstab(
    df['Contract'],
    df['Churn'],
)
tabela_cont_C

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [41]:
chi2, p_value, dof, expected = stats.chi2_contingency(tabela_cont_C)
chi2, p_value,dof, expected

(np.float64(1184.5965720837926),
 np.float64(5.863038300673391e-258),
 2,
 array([[2846.69175067, 1028.30824933],
        [1082.11018032,  390.88981968],
        [1245.198069  ,  449.801931  ]]))

### Resultado

Qui-quadrado tem `p-value < 0,05`, mostrando que existe associação entre **Contract** e **Churn**.

Os valores vistos também tem diferenças consideráveis em relação aos valores esperados caso as variáveis fossem independentes. Oque pode ser observado ao olhar para o valor `Expected`

Esse resultado mostra que tem diferença estatistica, assim como foi observado na análise exploratória.

## 4.2 **PaymentMethod** × **Churn**

In [43]:
tabela_cont_PM = pd.crosstab(
    df['PaymentMethod'],
    df['Churn'],
)
tabela_cont_PM

Churn                        No   Yes
PaymentMethod
Bank transfer (automatic)  1286   258
Credit card (automatic)    1290   232
Electronic check           1294  1071
Mailed check               1304   308

In [45]:
chi2, p_value, dof, expected = stats.chi2_contingency(tabela_cont_PM)
chi2, p_value,dof, expected

(np.float64(648.1423274814),
 np.float64(3.6823546520097993e-140),
 3,
 array([[1134.26891949,  409.73108051],
        [1118.10705665,  403.89294335],
        [1737.40025557,  627.59974443],
        [1184.22376828,  427.77623172]]))

### Resultado

Qui-quadrado tem `p-value < 0,05`, mostrando que existe associação entre **PaymentMethod** e **Churn**.

Os valores vistos também tem diferenças consideráveis em relação aos valores esperados caso as variáveis fossem independentes. O que pode ser observado ao olhar para o valor `Expected`.

Esse resultado mostra que tem diferença estatística, assim como foi observado na análise exploratória.

## 4.3 **InternetService** × **Churn**

In [46]:
tabela_cont_IS = pd.crosstab(
    df['InternetService'],
    df['Churn'],
)
tabela_cont_IS

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [47]:
chi2, p_value, dof, expected = stats.chi2_contingency(tabela_cont_IS)
chi2, p_value,dof, expected

(np.float64(732.309589667794),
 np.float64(9.571788222840544e-160),
 2,
 array([[1778.53954281,  642.46045719],
        [2274.41488002,  821.58511998],
        [1121.04557717,  404.95442283]]))

### Resultado

Qui-quadrado tem `p-value < 0,05`, mostrando que existe associação entre **InternetService** e **Churn**.

Os valores vistos também tem diferenças consideráveis em relação aos valores esperados caso as variáveis fossem independentes. O que pode ser observado ao olhar para o valor `Expected`.

Esse resultado mostra que tem diferença estatística, assim como foi observado na análise exploratória.

#5. Principais Resultados

## Variáveis numéricas

- **tenure**: o teste de Mann–Whitney mostrou `p-value = 2,42 × 10⁻²⁰⁸`, indicando diferença estatisticamente entre as distribuições de **tenure** dos grupos `Churn = Yes` e `Churn = No`.

- **MonthlyCharges**: o teste de Mann–Whitney mostrou `p-value = 3,31 × 10⁻⁵⁴`, indicando diferença estatisticamente entre as distribuições de **MonthlyCharges** dos grupos `Churn = Yes` e `Churn = No`.

- **TotalCharges**: o teste de Mann–Whitney mostrou `p-value = 5,69 × 10⁻⁸³`, indicando diferença estatisticamente entre as distribuições de **TotalCharges** dos grupos `Churn = Yes` e `Churn = No`.

## Variáveis categóricas

- **Contract**: Utilizado qui-quadrado e descobrimos `p-value = 5,86 × 10⁻²⁵⁸`, mostrando associação estatisticamente entre **Contract** e **Churn**.

- **PaymentMethod**: Utilizado qui-quadrado e descobrimos `p-value = 3,68 × 10⁻¹⁴⁰`, mostrando associação estatisticamente entre **PaymentMethod** e **Churn**.

- **InternetService**: Utilizado qui-quadrado e decobrimos `p-value = 9,57 × 10⁻¹⁶⁰`, mostrando associação estatisticamente entre **InternetService** e **Churn**.